-- Your SQL goes here
CREATE TABLE tables(
    id SERIAL PRIMARY KEY,
    active BOOLEAN NOT NULL
);

INSERT INTO tables VALUES(DEFAULT, False);
INSERT INTO tables VALUES(DEFAULT, False);
INSERT INTO tables VALUES(DEFAULT, False);
INSERT INTO tables VALUES(DEFAULT, False);
INSERT INTO tables VALUES(DEFAULT, False);
INSERT INTO tables VALUES(DEFAULT, False);
INSERT INTO tables VALUES(DEFAULT, False);